name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: "bhavik-dodda" # optional, but default will use the same from github
          CREDLY_SORT: "POPULAR" # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
          BADGE_SIZE: 100 # optional, 110x110 default
          NUMBER_LAST_BADGES: 24 # optional, will show the 48 in the first page
